let Number = 10.5;
let Number_ = 30;
console.log(Math.abs(-2));
console.log(Math.pow(2, 3));
console.log(Math.max(12, 9, 56, 3, 45, 23));
console.log(Math.floor(5.6));
console.log(Math.ceil(5.7));
console.log(Math.min(5, 6));
console.log(Math.PI);
console.log(Math.round(5.6));
console.log(Math.sqrt(25));
console.log(Math.sin(10));
console.log("Random Number:\t");
console.log(Math.round(Math.random() * 10000) + 10);